accounts/urls.py
from django.urls import path

from .views import UserRegisterView, UserProfileView, UserProfileEditView

app_name = "accounts"

urlpatterns = [
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/edit/", UserProfileEditView.as_view(), name="profile_edit"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls", namespace="news")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from .views import (
    IndexView,
    NewsPaperCreate,
    NewsPaperDetail,
    NewsPaperUpdate,
    UserNewsList,
    TopicList,
    TopicDetail,
    TopicCreate,
    TopicUpdate,
    NewsPaperDelete,
    TopicDelete,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("my-news/", UserNewsList.as_view(), name="my_news"),
    path("newspapers/<int:pk>/", NewsPaperDetail.as_view(), name="newspaper"),
    path("newspapers/<int:pk>/edit/", NewsPaperUpdate.as_view(), name="edit"),
    path("newspapers/create/", NewsPaperCreate.as_view(), name="create"),
    path(
        "newspapers/update/<int:pk>/", NewsPaperUpdate.as_view(), name="update"
    ),
    path(
        "newspapers/delete/<int:pk>/", NewsPaperDelete.as_view(), name="delete"
    ),
    path("topics/", TopicList.as_view(), name="topic-list"),
    path("topics/<int:pk>/", TopicDetail.as_view(), name="topic-detail"),
    path("topics/create/", TopicCreate.as_view(), name="topic-create"),
    path("topics/update/<int:pk>/", TopicUpdate.as_view(), name="topic-update"),
    path("topics/delete/<int:pk>/", TopicDelete.as_view(), name="topic-delete"),
]

app_name = "news"

templates/includes/menu.html
<div id="fh5co-offcanvass">
  <a href="#" class="fh5co-offcanvass-close js-fh5co-offcanvass-close">Menu <i class="icon-cross"></i></a>
  
  <div class="auth-block">
    {% if user.is_authenticated %}
      <a href="{% url 'accounts:profile' %}">
      <div class="user-info">
        <img src="{{ user.profile_image.url|default:'/static/images/no-avatar.png' }}" 
             alt="Profile" 
             class="profile-img">
        <span class="username">{{ user.username }}</span>
      </div>
      </a>
      <form action="{% url 'logout' %}" method="post" class="logout-form">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Вийти</button>
      </form>
    {% else %}
      <div class="auth-buttons">
        <a href="{% url 'login' %}" class="btn btn-primary btn-sm">Увійти</a>
        <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-sm">Реєстрація</a>
      </div>
    {% endif %}
  </div>

  <h1 class="fh5co-logo"><a class="navbar-brand" href="#">Editorial-Hub</a></h1>
  <ul>
    <li class="active">
      <a href="{% url 'news:index' %}">Додому</a>
    </li>
    <li>
      <a href="{% url 'news:my_news' %}">Мої Статті</a>
    </li>
    <li>
      <a href="{% url 'news:topic-list' %}">Теми</a>
    </li>
  </ul>
  <h3 class="fh5co-lead">Connect with us</h3>
  <p class="fh5co-social-icons">
    <a href="#"><i class="icon-twitter"></i></a>
    <a href="#"><i class="icon-facebook"></i></a>
    <a href="#"><i class="icon-instagram"></i></a>
    <a href="#"><i class="icon-dribbble"></i></a>
    <a href="#"><i class="icon-youtube"></i></a>
  </p>
</div>